Misc Documentation Updates
dortania/Anti-Hackintosh-Buyers-Guide pull request #16
Opened 2022-03-11 06:58 UTC by Church13

2022-05-13 05:44 UTC, 1Revenger1 requested changes
Looks good, just one change. Sorry about the long wait time :(

2022-05-13 05:44 UTC, 1Revenger1 commented on Wireless.md
> +* ~~Any Intel based wireless(Bluetooth sometimes works but it's inconsistent and seems to be on a per system basis)~~
I would just get rid of these two lines instead of striking them out.

2022-05-13 16:28 UTC, Church13 commented
> Looks good, just one change. Sorry about the long wait time :(

No problem! Busy time. Thanks for following up!

2022-05-15 04:04 UTC, 1Revenger1 approved these changes

2022-05-15 04:04 UTC, merged